### ISSUE TITLE
OS platform

### ISSUE THREAD

**Issue by jackiechensuper** [ShaoqingRen/SPP_net#11]
Hi Shaoqing,
Could the SPP net support the linux? Since I run the caffe in pre-requirement, I got the following make error:
./include/caffe/syncedmem.hpp: In constructor ‘caffe::SyncedMemory::SyncedMemory(size_t)’:
./include/caffe/syncedmem.hpp:67:10: warning: ‘caffe::SyncedMemory::size_’ will be initialized after [-Wreorder]
./include/caffe/syncedmem.hpp:65:10: warning:   ‘size_t caffe::SyncedMemory::cpu_capacity_’ [-Wreorder]
./include/caffe/syncedmem.hpp:43:12: warning:   when initialized here [-Wreorder]
python/caffe/_caffe.cpp: In member function ‘void caffe::PyNet::set_input_arrays(boost::python::api::object, boost::python::api::object)’:
python/caffe/_caffe.cpp:96:14: error: ‘MemoryDataLayer’ was not declared in this scope
python/caffe/_caffe.cpp:96:35: error: template argument 1 is invalid
python/caffe/_caffe.cpp:96:37: error: expected unqualified-id before ‘>’ token
python/caffe/_caffe.cpp:98:8: error: ‘md_layer’ was not declared in this scope
python/caffe/_caffe.cpp:108:50: error: ‘md_layer’ was not declared in this scope
make: **\* [python/caffe/_caffe.so] Error 1

**Comment by F0Z** [comment]
Can you provide some details on how to remove MemoryDataLayer from the python wrapper?
