### ISSUE TITLE
matcaffe in Linux

### ISSUE THREAD

**Issue by wistone** [ShaoqingRen/SPP_net#17]
Hi, Shaoqing

I have tried your code in Linux Ubuntu12.04. Since your provided matcaffe is for windows, I have downloaded the caffe package from https://github.com/ShaoqingRen/caffe/archive/master.zip

After built all the spp components, caffe and matcaffe, I tried to run the spp_demo, but I encounter the following problem.

^[zlibprotobuf ERROR google/protobuf/text_format.cc:172] Error parsing text-format caffe.NetParameter: 14:14: Message type "caffe.V0LayerParameter" has no field named "conv_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1121 20:39:26.828352 28307 upgrade_proto.cpp:627] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /media/Backup/SPP_net-master/data/cnn_model/Zeiler_conv5/Zeiler_spm_scale224_test_conv5.prototxt
**\* Check failure stack trace: ***
Killed

It seems the provided caffe is not suitable for your prototxt?

Could you kindly help solving this problem?

Thanks.

**Comment by ucasqcz** [comment]
i have the same problem ,but the model is downloaded by the fetch_model_data.m file,so do you have any suggestion"
Thanks.
