### ISSUE TITLE
Is it possible to run SPP on ubuntu?

### ISSUE THREAD

**Issue by jeromeyoon** [ShaoqingRen/SPP_net#23]
Hi everyone

I wanna use SPP on ubuntu 12.04.
However when i excute spp_buidl(),a error message appeared

Error using mex
/tmp/mex_2071126706256729_16132/tron.o: In function `TRON::trcg(double, double*, double*, double*)':
tron.cpp:(.text+0x1da): undefined reference to `dnrm2_'
tron.cpp:(.text+0x1fd): undefined reference to `ddot_'
tron.cpp:(.text+0x219): undefined reference to `dnrm2_'
tron.cpp:(.text+0x252): undefined reference to `ddot_'
tron.cpp:(.text+0x27a): undefined reference to `daxpy_'
tron.cpp:(.text+0x28a): undefined reference to `dnrm2_'
tron.cpp:(.text+0x2d9): undefined reference to `daxpy_'
tron.cpp:(.text+0x2ef): undefined reference to `ddot_'
tron.cpp:(.text+0x30a): undefined reference to `ddot_'
tron.cpp:(.text+0x325): undefined reference to `ddot_'
tron.cpp:(.text+0x3c6): undefined reference to `daxpy_'
tron.cpp:(.text+0x3f6): undefined reference to `daxpy_'
tron.cpp:(.text+0x427): undefined reference to `daxpy_'
tron.cpp:(.text+0x43d): undefined reference to `ddot_'
tron.cpp:(.text+0x460): undefined reference to `dscal_'
tron.cpp:(.text+0x47a): undefined reference to `daxpy_'

can anyone help me?

My system:
Ubuntu 12.04
Titan black
16 GB
Matlab R2014a

**Comment by wuxinhong** [comment]
https://onedrive.live.com/download?resid=4006CBB8476FF777!9459&authkey=!ALvSvUfuMLHmCoA&ithint=file%2czip,This site cannot be logged， I can not download the model
