### ISSUE TITLE
SPP_net can't finetune on ubuntu

### ISSUE THREAD

**Issue by wuqiangch** [ShaoqingRen/SPP_net#29]
Anyone can finetune it on ubuntu? I can finetune it on windows,but i can't  finetune it on ubuntu.Anyone can help me ?Thanks!

**Comment by danielruelle** [comment]
it is not related to your question, but how can you solve the problem of "API command not recognized" posted here https://github.com/ShaoqingRen/SPP_net/issues/26

I get the same error as yours.

Thanks.

**Comment by wuqiangch** [comment]
@danielruelle,You can use the files "https://github.com/ShaoqingRen/SPP_net, And https://github.com/ShaoqingRen/caffe" to solve the  solve the problem of "API command not recognized" .
