### ISSUE TITLE
spp_demo crashes at second time

### ISSUE THREAD

**Issue by danielruelle** [ShaoqingRen/SPP_net#31]
Hi @ShaoqingRen 

I have some discussions elsewhere, but I post here separately.

When I run spp_demo for the first time, it done welll. However, when I try spp_demo in the second time, Matlab crashes.

I log some printed lines and recognize that g = gpuDevice(1); failed, so I guess the GPU device has still not released after the first run.

Hope you can help to debug this error.

Thank you,

**Comment by wuqiangch** [comment]
Did you  restart the matlab and try again? It is OK if you restart the matlab？Are you sure Only you use the GPU?
