### ISSUE TITLE
Error using fliplr (line 18) X must be a 2-D matrix.

### ISSUE THREAD

**Issue by VirtualEarth** [ShaoqingRen/SPP_net#32]
hi ， there is an error when i use  Script_spp_voc.m and voc 2007 to train a mode ,i get a error 
Error using fliplr (line 18) X must be a 2-D matrix.  in  imwrite(fliplr(im), flip_image_at(i));
Since function fliplr is for 2-D matrix. , should I skip this sentence by setting parameter "flip" to false? Or should I use another function that is for 3D images? Or must I use gray images?

thanks.

**Comment by ShaoqingRen** [comment]
Hi @VirtualEarth,

The problem comes from matlab version. im(:, end:-1:1, :) can be used instead of fliplr()

**Comment by VirtualEarth** [comment]
oh, thank u
