### ISSUE TITLE
SPP_net must run by CUDA5.5,or Can still run byCUDA6.5 

### ISSUE THREAD

**Issue by ericeiffel** [ShaoqingRen/SPP_net#39]
I had install Cuda6.5 and new caffe version,so I want to sure SPP can still run OK? SPP mex is based on Cuda5.5?

**Comment by ShaoqingRen** [comment]
Yes, the provide mex is compiled with cuda 5.5. The new caffe verision can be compiled with any cuda version.

**Comment by ericeiffel** [comment]
Thank U ~ I will try cuda5.5 ^_^
