### ISSUE TITLE
Error in imdb_from_voc

### ISSUE THREAD

**Issue by AbdealiJK** [ShaoqingRen/SPP_net#47]
Get the following error when running Script_spp_voc  (The error is in imdb_from_voc)

```
Error using fliplr (line 18)
X must be a 2-D matrix.

Error in imdb_from_voc (line 55)
             imwrite(fliplr(im), flip_image_at(i));

Error in Script_spp_voc>perpare_train_data (line 89)
    opts.imdb_train             = {  imdb_from_voc(opts.devkit, 'trainval', '2007', flip) };

Error in Script_spp_voc (line 46)
opts                        = perpare_train_data(opts, opts.flip | opts.flip_finetune);
```

When I check the data, the image is a 3D matrix.

**Comment by ShaoqingRen** [comment]
Hi @AbdealiJK,

The problem comes from matlab version. im(:, end : -1 : 1, :) can be used instead of fliplr()

**Comment by AbdealiJK** [comment]
Ah, You are right.
I used `flipdim(im, 2)` which is supposed to have better performance :)
