### ISSUE TITLE
Dropout ratio change for SPP caffe version not accounted in deployment

### ISSUE THREAD

**Issue by legolas123** [ShaoqingRen/SPP_net#51]
Since in the SPP caffe version, scaling in dropout layer during training is not happening and it has been shifted to test phase, doesnt spp_poolX_to_fcX.m should scale the feat appropriately after the max(0,feat) operation.

**Comment by ShaoqingRen** [comment]
@legolas123, absolutely you are right. We realized this issue nearly when doing external tester. We experimentally verified the difference between  w/o scale the feat, it will lead in around 0.5 changes on mAP. But considering, all of models in caffe ZOO is doing scaling in training, which is compatible with current spp code. So maybe current spp code is more suitable for caffe forks (expect ours).

**Comment by legolas123** [comment]
Ok, that seems correct. 
Thanks
